spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: fa#4DG6^G
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: c2RydmFzZGZua2Ezdzs0b25hZmxrYXNkO2xma21zYWw7ZkxLTkxLQVdORkxBTkVHRlM7RUZMS1NORjtTRExGS0RTRg==
    access: 3600000
    refresh: 2592000000